services:
  worker:
    depends_on:
      traefik:
        condition: service_started
      minio:
        condition: service_healthy
      denokv:
        condition: service_started
      redis:
        condition: service_healthy
    entrypoint: ["deno", "run", "--unsafely-ignore-certificate-errors", "--watch", "--allow-all", "src/cli.ts"]
    command: run --mode=local --cpus=2 --gpus=0 local1
    working_dir: /app/worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - "8000"
    ports:
      - "8081:8000"
    build:
      context: .
      dockerfile: worker/Dockerfile
      target: worker
    environment:
      - PORT=8000
      - IGNORE_CERTIFICATE_ERRORS=true
      - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-}
      - DENO_DIR=/deno
      - DENO_INSTALL_ROOT=/deno
    volumes:
      - ./shared:/app/shared
      - ./worker:/app/worker
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - deno:/deno
      - node_modules_worker:/app/worker/node_modules
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway
      - local.storage.local.nhost.run:host-gateway
      - minio.worker-metaframe.localhost:host-gateway
      - worker-metaframe.localhost:host-gateway
    labels:
      - "custom.label=worker-metaframe.localhost"
      - "traefik.enable=true"
      - "traefik.http.routers.worker.rule=Host(`worker-metaframe.localhost`)"
      - "traefik.http.routers.worker.tls=true"
      - "traefik.http.routers.worker.entrypoints=websecure"
      - "traefik.http.services.worker.loadbalancer.server.port=8000"
      - "traefik.http.services.worker.loadbalancer.server.scheme=http"
    logging:
      driver: ${LOGGING_WORKER:-json-file}

  create-browser-assets:
    build:
      context: .
      dockerfile: browser/Dockerfile
    command: just watch
    working_dir: /app/browser
    environment:
      - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-}
      - SERVER_ORIGIN=https://worker-metaframe.localhost:${APP_PORT:-443}
    volumes:
      - ../.git:/.git
      - ./browser/dist:/app/browser/dist
      - ./browser/index.html:/app/browser/index.html
      - ./browser/justfile:/app/browser/justfile
      - ./browser/package-lock.json:/app/browser/package-lock.json
      - ./browser/package.json:/app/browser/package.json
      - ./browser/public:/app/browser/public
      - ./browser/src:/app/browser/src
      - ./browser/tsconfig.json:/app/browser/tsconfig.json
      - ./browser/vite.config.ts:/app/browser/vite.config.ts
      - ./shared:/app/shared
      - node_modules:/app/browser/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  deno:
    driver: local
  node_modules:
    driver: local
  node_modules_worker:
    driver: local

networks:
  default:
    driver: bridge
