# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'metapage-workers-b'
primary_region = 'iad'

[build]
  dockerfile = './worker/Dockerfile'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[env]
  METAPAGE_WORKER_CPUS = '2'

[[metrics]]
  port = 8000
  path = '/metrics'

[[restart]]
  policy = "never"
  retries = 10
