# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'metapage-workers-a'
primary_region = 'iad'

[build]
  dockerfile = './worker/Dockerfile'
  build-target = 'worker-standalone'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  METAPAGE_WORKER_CPUS = 1

[metrics]
  port = 8000
  path = "/metrics"

[[restart]]
  policy = "never"
  retries = 10
