set shell := ["bash", "-c"]
set dotenv-load := true

# minimal formatting, bold is very useful

bold := '\033[1m'
normal := '\033[0m'
green := "\\e[32m"
yellow := "\\e[33m"
blue := "\\e[34m"
magenta := "\\e[35m"
grey := "\\e[90m"

@_help:
    set -euo pipefail
    echo -e ""
    just --list --unsorted --list-heading $'🌱 Fly.io:\n\n'
    echo -e ""
    echo -e "        Monitor GPU queue:   {{ green }}https://fly.io/apps/metapage-io-workers-a/monitoring{{ normal }}"
    echo -e "        Monitor CPU queue:   {{ green }}https://fly.io/apps/metapage-io-workers-b/monitoring{{ normal }}"
    echo -e "        Monitor Autoscaler:  {{ green }}https://fly.io/apps/metapage-io-autoscaler/monitoring{{ normal }}"

    echo -e ""

# Deploy the GPU and CPU workers
deploy: deploy-gpu deploy-cpu

# Deploy the GPU workers
deploy-gpu:
    fly deploy -c workers-a.fly.toml --yes --ha=false

# Deploy the CPU workers
deploy-cpu:
    fly deploy -c workers-b.fly.toml --yes --ha=false
