app = 'metapage-fly-metrics-proxy'
primary_region = 'ord'

[build]
  image = 'docker.io/michaelendsley/fly-metrics-proxy:latest'

[env]
  METRICS_TARGETS = """
[
  {
    "endpoint": "https://container.mtfm.io/[queue_id]/metrics",
    "app_name": "metapage-workers-a"
  },
  {
    "endpoint": "https://container.mtfm.io/[queue_id]/metrics",
    "app_name": "metapage-workers-b"
  }
]
"""

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 8080
  path = '/metrics'
  https = false
