# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'metapage-workers-b'
primary_region = 'ord'

[build]
#  image = 'metapage/metaframe-docker-worker:latest-standalone'
  image = 'michaelendsley/worker-standalone:0.3.14'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[env]
  METAPAGE_WORKER_CPUS = '2'
  METAPAGE_WORKER_RUN_STANDALONE = true

[[restart]]
  policy = "on-failure"
  retries = 10
