# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'metapage-io-workers-b'
primary_region = 'ord'

[build]
  image = 'metapage/metaframe-docker-worker:0.54.0-standalone'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[env]
  METAPAGE_IO_WORKER_CPUS = '2'
  METAPAGE_IO_WORKER_RUN_STANDALONE = true
  # METAPAGE_IO_QUEUE_ID is set as a secret

[[restart]]
  policy = "on-failure"
  retries = 10
