# Always use locally installed tools (always pin versions)

set shell := ["bash", "-c"]
set dotenv-load := true
set export := true

# minimal formatting, bold is very useful

bold := '\033[1m'
normal := '\033[0m'

@_help:
    just --list --unsorted --list-heading $'Commands:\n'
    echo -e ""

# Quick compile checks
@check:
    deno check src/mod.ts
    echo "✅ shared typescript compilation"

# Lint
@lint:
    deno lint

# Lint and fix issues
@lint-fix:
    deno lint --fix

# Format
@fmt:
    deno fmt

# Format check
@fmt-check:
    deno fmt --check

# Fix
@fix: lint-fix fmt

@test:
    deno test --allow-all --unstable-kv --unstable-cron src

@build:
    deno task build

# Run CI
@ci: fmt-check lint
