name: fmt check

on:
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Just CLI
        uses: extractions/setup-just@v1
        with:
          just-version: "1.35.0"

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.4

      - name: Check formatting
        run: just fmt --check
