# .yaml files in this directory are executed workflows:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# This workflow is triggered on pushes to non-main (or master) branches
# Builds and tests the app (just test)
name: Test (self-hosted)

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    # only non-main (and non-master) branches
    branches:
      - "**"
      - "!main"
      - "!master"

jobs:
  test_remote_mode:
    name: remote mode
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: test
        run: just test remote
        timeout-minutes: 20

  test_local_mode:
    name: local mode
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: test
        run: just test local
        timeout-minutes: 20
